name: bloggios_app

description: "Bloggios Application"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  icons_plus: ^5.0.0
  go_router: ^14.6.2
  flutter_bloc: ^8.1.6
  fpdart: ^1.1.1
  http: ^1.2.2
  dio: ^5.7.0
  get_it: ^8.0.2
  flutter_secure_storage: ^9.2.2
  loading_animation_widget: ^1.3.0
  quickalert: ^1.1.0
  lottie: ^3.3.0
  pinput: ^5.0.0
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.1
  loader_overlay: ^5.0.0
  flutter_native_splash: ^2.4.4
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.16
  intl: ^0.20.1
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - .env
    - assets/vectors/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/nunito/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/nunito/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/nunito/Nunito-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/nunito/Nunito-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/nunito/Nunito-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/nunito/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/nunito/Nunito-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/nunito/Nunito-ExtraLightItalic.ttf
          weight: 200
          style: italic

flutter_native_splash:
  color: "#5464ff" # Background color
  image: assets/images/bloggios_logo.png
  android: true # Include Android platform
  ios: true # Include iOS platform
  web: false # Exclude web
  android_gravity: center # Center logo on Android
  ios_content_mode: center # Center logo on iOS
  image_ios: assets/images/bloggios_logo_white.png
  image_dark_ios: assets/images/bloggios_logo_white.png
  android_12:
    color: "#5464ff" # Background color
    icon_background_color: "#000000"
    icon_background_color_dark: "#000000"
